// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.Config>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function SetConfig(arg1:main.Config):Promise<void>;
