// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['Ncn']['GetConfig']();
}

export function Search(arg1) {
  return window['go']['main']['Ncn']['Search'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['main']['Ncn']['SetConfig'](arg1);
}
